/**
 * The controller class for the Identify Page in the GUI.
 * This class handles user interactions and events on the Identify Page GUI.
 */
package gui;

import java.util.regex.Matcher;
import java.util.regex.Pattern;

import client.ChatClient;
import entity.NextPage;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.scene.control.Button;
import javafx.scene.control.TextField;
import javafx.scene.text.Text;

public class IdentifyPageController {

	    @FXML
	    private Button btnBack;

	    @FXML
	    private Button btnExit;

	    @FXML
	    private Button btnIdntefy;

	    @FXML
	    private Text errorTxt;

	    @FXML
	    private TextField identify_id;

	    /**
	     * Event handler for the "Identify" button.
	     * It checks the validity of the identification number provided by the user
	     * and proceeds to the next page if the identification number contains only digits.
	     *
	     * @param event The ActionEvent generated by clicking the "Identify" button.
	     */
	    //Event for "Identify" button
	    @FXML
	    void pressIdentifyBtn(ActionEvent event) {
	    	try {
	    		String identNum = this.identify_id.getText();
	    		
	    		// Check if the string contains any digit
	            Pattern pattern = Pattern.compile("\\d+");
	            Matcher matcher = pattern.matcher(identNum);
	            boolean containsOnlyDigits = matcher.matches();
	            if (containsOnlyDigits) {
	                ChatClient.visitorID = identNum;
	                NextPage page = new NextPage(event, "/gui/TravellerPage.fxml", "Traveller Page",
	                        "TravellerPageController", "pressIdentifyBtn");
	                page.Next();
	            }else {
	                throw new IllegalArgumentException("Identification number not valid.");
	            }
		        		    	
	    	}catch (IllegalArgumentException e) {
	    		System.out.println("Identification number wrong.");
	    		this.errorTxt.setText(e.getMessage());
	    	}catch (Exception e) {
	    		System.out.println("Error in IdentifyPageController: pressIdentifyBtn");
	    	}
	    }
	    
	    /**
	     * Event handler for the "Back" button.
	     * It sets the visitor ID to an empty string and navigates back to the Home Page.
	     *
	     * @param event The ActionEvent generated by clicking the "Back" button.
	     * @throws Exception If an error occurs during the navigation.
	     */
	    //Event for "Back" button
	    @FXML
	    void pressBackBtn(ActionEvent event) throws Exception {
	    	try {
		    	//set visitor ID as ""
		    	ChatClient.visitorID = "";
		    	NextPage page = new NextPage(event, "/gui/NewHomePage.fxml", "Home Page", "NewHomePageController", "pressBackBtn");
		    	page.Next();
	    	}catch (Exception e) {
	    		System.out.println("Error in IdentifyPageController: pressBackBtn");
	    	}

	    }

	    /**
	     * Event handler for the "Exit" button.
	     * It terminates the application when the "Exit" button is clicked.
	     *
	     * @param event The ActionEvent generated by clicking the "Exit" button.
	     * @throws Exception If an error occurs during the termination of the application.
	     */
	    @FXML
		// Event for "Exit" button
		public void pressExitBtn(ActionEvent event) throws Exception {
			System.out.println("Exit Identify Page");
			System.exit(0);
		}

	}


 