/**
 * The controller class for the New Home Page GUI.
 * This class handles user interactions and events on the New Home Page GUI.
 */
package gui;
import entity.NextPage;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.scene.control.Button;

public class NewHomePageController {

    @FXML
    private Button btnExit;

    @FXML
    private Button btnIdentify;

    @FXML
    private Button btnLogin;

    /**
     * Event handler for the "Log in as an employee" button.
     * It navigates to the Login page when the button is clicked.
     *
     * @param event The ActionEvent generated by clicking the "Log in as an employee" button.
     * @throws Exception If an error occurs during the navigation.
     */
    //Event for "Log in as an employee"
    @FXML
    void pressLoginBtn(ActionEvent event) throws Exception {
    	try {
        	NextPage page = new NextPage(event, "/gui/Login.fxml", "", "LoginController", "pressLoginBtn");
        	page.Next();
    	}catch (Exception e) {
    		System.out.println("Error in NewHomePageController: pressLoginBtn");
    		System.out.println(e.getMessage());
    	}
    }

    /**
     * Event handler for the "Identify as a traveller" button.
     * It navigates to the Identify Page when the button is clicked.
     *
     * @param event The ActionEvent generated by clicking the "Identify as a traveller" button.
     * @throws Exception If an error occurs during the navigation.
     */
    //Event for "Identify as a traveller"
    @FXML
    void pressIdentifyBtn(ActionEvent event) throws Exception {
        try {
            NextPage page = new NextPage(event, "/gui/IdentifyPage.fxml", "Identify Page", "IdentifyPageController", "pressIdentifyBtn"); 
            page.Next();
        }catch (Exception e) {
            System.out.println("Error in NewHomePageController: pressIdentifyBtn");
            System.out.println(e.getMessage());
        }
    }


    /**
     * Event handler for the "Exit" button.
     * It terminates the application when the "Exit" button is clicked.
     *
     * @param event The ActionEvent generated by clicking the "Exit" button.
     * @throws Exception If an error occurs during the termination of the application.
     */
	// Event for "Exit" button
	public void pressExitBtn(ActionEvent event) throws Exception {
		System.out.println("Exit Home Page");
		System.exit(0);
	}
}
