/**
 * Controls the functionality of the settings page GUI.
 * It handles connecting to the server and exiting the application.
 */
package gui;

import java.util.ArrayList;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import client.ChatClient;
import client.ClientController;
import client.ClientUI;
import entity.NextPage;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.scene.control.TextField;
//import javafx.scene.image.ImageView;

import javafx.scene.text.Text;
import javafx.stage.Stage;

public class SettingsPageController {

	// labels
	@FXML
	private Label lblWellcome;

	// buttons
	@FXML
	private Button btnConnectToServer = null;
	@FXML
	private Button btnExit = null;

	// text fields
	@FXML
	private TextField txtIpAddress;
	@FXML
	private TextField txtPortNumber;

	@FXML
	private Text errorTxt;

    /**
     * Starts the settings page GUI.
     *
     * @param primaryStage The primary stage of the application.
     * @throws Exception If an error occurs during startup.
     */
	public void start(Stage primaryStage) throws Exception {
		try {
			Parent root = FXMLLoader.load(getClass().getResource("/gui/SettingsPage.fxml"));
			Scene scene = new Scene(root);


			primaryStage.setTitle("Settings Page");
			primaryStage.setScene(scene);

			primaryStage.show();

		} catch (Exception e) {
			System.out.println("Error in SettingsPageController: start");
			System.out.println(e.getMessage());
		}
	}

    /**
     * Handles the action when the "Connect" button is pressed to connect to the server.
     *
     * @param event The action event generated by pressing the connect button.
     * @throws Exception If an error occurs during connection.
     */
	// Event for "connect" button
public void connectToServer(ActionEvent event) throws Exception {
		
		try {
			String address = txtIpAddress.getText(), portNum = txtPortNumber.getText();

			if (address.trim().isEmpty() || portNum.trim().isEmpty()) {
				System.out.println("You must enter ip address and port number");
				errorTxt.setText("you must enter ip address and port number in order to connect to server");
				txtIpAddress.setText("");
				txtPortNumber.setText("");
			} else {
				try {
					ArrayList<Object> arrmsg = new ArrayList<Object>();
					arrmsg.add(new String("ConnectToServer"));
					arrmsg.add(new String("String"));
					arrmsg.add(new String("Conect"));
					ClientUI.chat = new ClientController(address, Integer.valueOf(portNum));
					ClientUI.chat.accept(arrmsg);
					
				} catch (Exception e) {
					System.out.println("you must enter valid ip and port numbers");
					errorTxt.setText("you must enter valid ip address and valid port number in order to connect to server");
					txtIpAddress.setText("");
					txtPortNumber.setText("");
					return;
				}
				if (ChatClient.result) {
					ChatClient.result = false;
					NextPage page = new NextPage(event, "/gui/NewHomePage.fxml", "Home Page", "NewHomePageController", "connectToServer"); //need to add path and title
					page.Next();
			    	
				} else {
					System.out.println("couldnt connect to server");
				}
			}
		}catch (Exception e) {
			System.out.println("Error in SettingsPageController: connectToServer");
		}
		

	}

    /**
     * Handles the action when the "Exit" button is pressed to exit the application.
     *
     * @param event The action event generated by pressing the exit button.
     * @throws Exception If an error occurs during application exit.
     */
	// Event for "Exit" button
	public void pressExitBtn(ActionEvent event) throws Exception {
		System.out.println("Exit Home Page");
		System.exit(0);
	}

}
