
/**
 * Controls the functionality of the SMS confirmation GUI.
 * It handles loading SMS messages, approving or canceling orders, and closing the window.
 */
package gui;

import java.util.ArrayList;

import client.ChatClient;
import client.ClientUI;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.scene.control.Button;
import javafx.scene.text.Text;
import javafx.stage.Stage;

public class SMSController {
	
	public enum Action {
		REMIND, CANCEL
	}

    @FXML
    private Button btnApprove;

    @FXML
    private Button btnClose;
    
    @FXML
    private Button btnCancel;

    @FXML
    private Text txtMsg;

    @FXML
    private Text txtResult;
    
    private String orderID;
    
    /**
     * Loads SMS message and adjusts UI elements accordingly.
     *
     * @param smsMsg The SMS message containing action, order ID, and message content.
     */
    public void loadSMS(ArrayList<String> smsMsg) {
    	try {
    		
    		//smsMsg {0- Action, 1 - OrderID, 2 - msg}
    		   		
    		if(smsMsg.equals("null"))
    			throw new NullPointerException("No message");

    		if(smsMsg.get(0).equals(Action.CANCEL.toString())) {
    			this.btnApprove.setVisible(false);
    			this.btnCancel.setVisible(false);
    		}
    			
    		//get order ID
    		this.orderID = smsMsg.get(1);
    		//set message
    		this.txtMsg.setText(smsMsg.get(2));
    		
    	}catch (Exception e) {
    		System.out.println("Error in SMSController: loadSMS");
    		System.out.println(e.getMessage());	
    	}
    }
    
    /**
     * Handles the action when the "Approve" button is pressed.
     *
     * @param event The action event generated by pressing the approve button.
     */
    //Event for "Approve" button
    @FXML
    void pressApproveBtn(ActionEvent event) {
   	
		try {
			ArrayList<Object> arrmsg = new ArrayList<Object>();
			arrmsg.add(new String("OrderApprove"));
			arrmsg.add(new String("String"));
			arrmsg.add(orderID);
			ClientUI.chat.accept(arrmsg);
			
			if(ChatClient.result == true)
				this.txtMsg.setText("Order approved successfully");
			else
				this.txtMsg.setText("Order wasn't approved");
			
			//hide cancel button
			this.btnApprove.setVisible(false);
			this.btnCancel.setVisible(false);
		} catch (Exception e) {
			System.out.println("Error in SMSController: pressApproveBtn");
			System.out.println(e.getMessage());
		}
    }
    

    /**
     * Handles the action when the "Cancel" button is pressed.
     *
     * @param event The action event generated by pressing the cancel button.
     */
    @FXML
    void pressCancelBtn(ActionEvent event) {
    	try {
			ArrayList<Object> arrmsg = new ArrayList<Object>();
			arrmsg.add(new String("OrderCancel"));
			arrmsg.add(new String("String"));
			arrmsg.add(orderID);
			ClientUI.chat.accept(arrmsg);
			
			if(ChatClient.result == true)
				this.txtMsg.setText("Order cancelled");
			else
				this.txtMsg.setText("Order wasn't cancelled");
			
			//hide button
			this.btnApprove.setVisible(false);
			this.btnCancel.setVisible(false);
    	}catch (Exception e) {
    		System.out.println("Error in SMSController: pressCancelBtn");
    		System.out.println(e.getMessage());
    	}
    }
    
    /**
     * Handles the action when the "Close" button is pressed.
     *
     * @param event The action event generated by pressing the close button.
     */
    @FXML
    void pressCloseBtn(ActionEvent event) {
    	try {
    		Button btn = (Button) event.getSource();
    		Stage stage = (Stage) btn.getScene().getWindow();
    		stage.close();
    	}catch (Exception e) {
    		System.out.println("Error in SMSController: pressCloseBtn");
    		System.out.println(e.getMessage());
    	}
    }
}
