/**
 * Controls the functionality of the total visitors number report page GUI.
 * It handles loading data for the report, displaying error messages, and closing the window.
 */
package gui;

import java.time.YearMonth;
import java.util.ArrayList;
import java.util.Random;

import client.ChatClient;
import client.ClientUI;
import javafx.beans.property.SimpleStringProperty;
import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.scene.chart.PieChart;
import javafx.scene.control.Button;
import javafx.scene.text.Text;
import javafx.stage.Stage;
import javafx.scene.control.TableColumn;
import javafx.scene.control.TableView;

public class TotalVisitorsNumberReportPageController {
    @FXML
    private PieChart pieChartReport;
    
    @FXML
    private Button btnClose;

    @FXML
    private Text txtMonth, txtYear, txtTotal, txtError;

    private ArrayList<String> dataForReport;
    //data report = {0 - parkName, 1 - month, 2 - year
    
    /**
     * Load report data into the table.
     *
     * @param dataForReport The data for the report, containing park name, month, and year.
     */
    //load report data
    public void loadData(ArrayList<String> dataForReport) {
    	try {    		
			this.dataForReport = dataForReport;
			this.txtMonth.setText(dataForReport.get(1));
			this.txtYear.setText(dataForReport.get(2));
			
    		//create order
			ArrayList<Object> arrmsg = new ArrayList<Object>();
			arrmsg.add(new String("CreateVisitorsNumReport"));
			arrmsg.add(new String("String"));
			arrmsg.add(dataForReport.get(0));
			ClientUI.chat.accept(arrmsg);
				
			
			this.txtError.setText("Report created successfully");

			//get dates from DB
			ArrayList<String> dataForRep = new ArrayList<String>();
			dataForRep.add(dataForReport.get(0)); //parkName
			dataForRep.add(dataForReport.get(1)); //month
			dataForRep.add(dataForReport.get(2)); //year
			
			arrmsg = new ArrayList<Object>();
			arrmsg.add(new String("GetVisitorsNumReport"));
			arrmsg.add(new String("ArrayList<String>"));
			arrmsg.add(dataForRep);
			ClientUI.chat.accept(arrmsg);
			
			if(ChatClient.dataFromServer.get(0).equals("null"))
				throw new NullPointerException("No report returned from DB");
    		
			
            // Insert data to the PieChart
            int privateVisitors = Integer.parseInt(ChatClient.dataFromServer.get(0));
            int groupVisitors = Integer.parseInt(ChatClient.dataFromServer.get(1));
            
            // Create the PieChart data
            ObservableList<PieChart.Data> pieChartData = FXCollections.observableArrayList(
                    new PieChart.Data("Private Visitors", privateVisitors),
                    new PieChart.Data("Group Visitors", groupVisitors)
            );
            
            
            // Create the PieChart
            this.pieChartReport.setData(pieChartData);
            
            // Display numbers on chart
            for (PieChart.Data data : this.pieChartReport.getData()) {
                data.setName(data.getName() + " (" + (int)data.getPieValue() + ")");
            }
            
            Integer intTotalVisitors = privateVisitors + groupVisitors;           
            this.txtTotal.setText(intTotalVisitors.toString());

			
		}catch(IllegalArgumentException e) {
			this.txtError.setText(e.getMessage());
		}
    	catch (Exception e) {
			System.out.println("Error in TotalVisitorsNumberReportPageController: loadData");
			System.out.println(e.getMessage());
		}	
    }
    

    /**
     * Handles the action when the "Close" button is pressed.
     *
     * @param event The action event generated by pressing the close button.
     */
    //Event for "Close" button
    @FXML
    void pressCloseBtn(ActionEvent event) {
    	try {
    		Button btn = (Button) event.getSource();
    		Stage stage = (Stage) btn.getScene().getWindow();
    		stage.close();
    	}catch (Exception e) {
    		System.out.println("Error in TotalVisitorsNumberReportPageController: pressCloseBtn");
    		System.out.println(e.getMessage());
    	}
    }

}
