/**
 * Controls the functionality of the traveller page GUI.
 * It handles button actions for cancelling, checking, placing a new order, and navigation.
 */
package gui;

import client.ChatClient;
import entity.NextPage;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.scene.control.Button;
import javafx.scene.image.ImageView;

public class TravellerPageController {

    @FXML
    private Button btnBack;

    @FXML
    private Button btnCancelling;

    @FXML
    private Button btnChecking;

    @FXML
    private Button btnExit;

    @FXML
    private Button btnNewOrder;

    @FXML
    private ImageView goIMG;

    /**
     * Handles the action when the "Cancelling an order" button is pressed.
     *
     * @param event The action event generated by pressing the cancelling button.
     */
    //Event for "Cancelling an order" button
    @FXML
    void pressCancellingBtn(ActionEvent event) throws Exception {
    	try {
			//visitorID instead of method
			NextPage page = new NextPage(event, "/gui/FindOrderFrame.fxml", "Find order", "FindOrderFrameController", "pressCancellingBtn", FindOrderFrameController.Action.CANCEL);
			page.Next();
		} catch (Exception e) {
    		System.out.println("Error in TravellerPageController: pressCancellingBtn");
    		System.out.println(e.getMessage());
		}
    }
    
    /**
     * Handles the action when the "Checking and editing an existing order" button is pressed.
     *
     * @param event The action event generated by pressing the checking button.
     */
    //Event for "Checking and editing an existing order" button
    @FXML
    void pressCheckingBtn(ActionEvent event) throws Exception {
    	try {
    		//visitorID instead of method
    		NextPage page = new NextPage(event, "/gui/FindOrderFrame.fxml", "Find order", "FindOrderFrameController", "pressCheckingBtn", FindOrderFrameController.Action.EDIT);
        	page.Next();
    	}catch (Exception e) {
    		System.out.println("Error in TravellerPageController: pressCheckingBtn");
    		System.out.println(e.getMessage());
    	}
    }

    /**
     * Handles the action when the "Placing a new order" button is pressed.
     *
     * @param event The action event generated by pressing the new order button.
     */
    //Event for "Placing a new order" button
    @FXML
    void pressNewOrderBtn(ActionEvent event) throws Exception {
    	NextPage page = new NextPage(event, "/gui/CreateOrderForm.fxml", "Create new order", "CreateOrderFrameController", "pressNewOrderBtn");
    	page.Next();
    }
    
    /**
     * Handles the action when the "Back" button is pressed.
     *
     * @param event The action event generated by pressing the back button.
     */
    //Event for "Back" button
    @FXML
    void pressBackBtn(ActionEvent event) throws Exception {
    	//set visitor ID as ""
    	ChatClient.visitorID = "";
    	NextPage page = new NextPage(event, "/gui/IdentifyPage.fxml", "Identify Page", "IdentifyPageController", "pressIdentifyBtn"); 
    	page.Next();
    }
    
    /**
     * Handles the action when the "Exit" button is pressed.
     *
     * @param event The action event generated by pressing the exit button.
     */
	// Event for "Exit" button
	public void pressExitBtn(ActionEvent event) throws Exception {
		System.out.println("Exit Home Page");
		System.exit(0);
	}

}
